### ISSUE TITLE
Api error

### ISSUE THREAD

**Issue by dezmou** [ddworken/hishtory#107] opened 2023-09-14 09:11 UTC
Hey, look like your API is down

```
2023/09/14 11:08:33 hishtory fatal error at github.com/ddworken/hishtory/hishtory.go:386: failed to POST /api/v1/submit?source_device_id=**masked**: Post "https://api.hishtory.dev/api/v1/submit?source_device_id=**masked**": net/http: TLS handshake timeout
```

Also running hishtory uninstall make this : 

```
2023/09/14 11:08:12 hishtory fatal error at github.com/ddworken/hishtory/hishtory.go:264: unknown command: uninstall
```

**Comment by kolluria** [comment] 2023-09-15 05:08
Hi,

I can confirm that this issue is still occurring. I had to disable hishtory since I keep seeing curl command failures every time I ran a command.
Also, it looks like `https://api.hishtory.dev/healthcheck` is down too.

**Comment by kolluria** [comment] 2023-09-15 05:10
Pasting the error message from my terminal - 
```
2023/09/15 10:38:55 hishtory v0.206 fatal error at github.com/ddworken/hishtory/client/cmd/query.go:58: failed to GET https://api.hishtory.dev/api/v1/get-deletion-requests?user_id=xxxx=&device_id=xxxx: Get "https://api.hishtory.dev/api/v1/get-deletion-requests?user_id=xxxx&device_id=xxxx": dial tcp 167.99.24.52:443: connect: connection refused
```

**Comment by aleksandergrzyb** [comment] 2023-09-15 05:11
Same for me:
```
2023/09/15 07:10:43 hishtory v0.193 fatal error at github.com/ddworken/hishtory/client/cmd/saveHistoryEntry.go:98: failed to POST /api/v1/submit?source_device_id=4b1e8c77-ac72-4172-9fe2-cb2563b5f57b: Post "https://api.hishtory.dev/api/v1/submit?source_device_id=4b1e8c77-ac72-4172-9fe2-cb2563b5f57b": dial tcp 167.99.24.52:443: connect: connection refused
```

**Comment by aleksandergrzyb** [comment] 2023-09-15 05:12
Same for me:
```
2023/09/15 07:10:43 hishtory v0.193 fatal error at github.com/ddworken/hishtory/client/cmd/saveHistoryEntry.go:98: failed to POST /api/v1/submit?source_device_id(...)
```

**Comment by isjarvi** [comment] 2023-09-15 05:31
this is a local running software, why need to post to the external network?

**Comment by ddworken** [comment] 2023-09-15 05:45
My apologies everyone, the server has now been fixed and is operational again. It seems like the Digitalocean instance that was running the backend got killed by Digitalocean (it seems to currently be stuck in a weird state where it is neither online nor offline), so I ended up having to restore from backups and create a new server. The good news is that the restore went off without a hitch and everything is now back up and running without any data loss. 

In addition, if you run `hishtory update` you will get the latest version of `hishtory` which will properly handle errors of this type without spamming your terminal.

**Comment by ddworken** [comment] 2023-09-15 05:47
> this is a local running software, why need to post to the external network?

The network requests are used for syncing support, so that if you install hishtory on another one of your machines (and securely copy over your cryptographic key used for identification and encrypting all data), you can share your shell history across all your machines. If you aren't interested in syncing, it is also possible to install hishtory in a fully offline mode (see "Offline Install") in the readme.

**Comment by ddworken** [comment] 2023-09-15 05:48
For anyone curious, here is the Synthetics graph from Datadog showing that the outage lasted ~1.5 hours and has now been fully fixed. 

<img width="1251" alt="Screenshot 2023-09-14 at 10 47 50 PM" src="https://github.com/ddworken/hishtory/assets/5304541/af7da4c3-2e90-411e-907d-6c8fa131d0a3">

**Comment by ddworken** [comment] 2023-09-20 01:45
Resolving since the API has been back up and stable for the last 5 days.

**Closed by ddworken** 2023-09-20 01:45 UTC

**Comment by elvismacak** [comment] 2024-03-13 07:04
> > this is a local running software, why need to post to the external network?
> 
> The network requests are used for syncing support, so that if you install hishtory on another one of your machines (and securely copy over your cryptographic key used for identification and encrypting all data), you can share your shell history across all your machines. If you aren't interested in syncing, it is also possible to install hishtory in a fully offline mode (see "Offline Install") in the readme.

same problem here.  After reading the code, i found it can be update through the config file `~/.hishtory/.hishtory.config` with setting is_offline to true.   Can help update the doc or add config-get commands ?
