### ISSUE TITLE
Database errors after upgrade

### ISSUE THREAD

**Issue by github-cli** [ddworken/hishtory#242] opened 2024-09-01 07:27 UTC
after upgrading hishtory it no longer works, I tried an older version but still have issues
the hishtory server healthcheck fails and is not reachable

Description:    Ubuntu 22.04.4 LTS
Docker version 27.2.0, build 3ab4256
Docker Compose version v2.20.3
CPU Model name: 12th Gen Intel(R) Core(TM) i9-12900H
MemTotal: 32597184 kB

compose file:
http://dpaste.com//HBR3LP6UF
hishtory server container logs:
http://dpaste.com//BU78G8P3A
postgres container logs:
http://dpaste.com//HH98GBMYR

I tried going back to an older version of hishtory but that did not change anything...

**Comment by ddworken** [comment] 2024-09-01 19:36
Thank you for the detailed bug report and logs! I'm looking into this now, but closing this as a dupe of #241 so I can document my investigation in one place.

**Closed by ddworken** 2024-09-01 19:36 UTC

**Comment by ddworken** [comment] 2024-09-01 22:13
Ok, this should now be fixed with the latest release! Please give it a try and let me know if you're still running into any issues. 

And just FYI, thanks to hishtory's syncing design, you shouldn't lose any state even if your server was offline for an extended period of time due to this issue.
