### ISSUE TITLE
Hishtory API offline + not able to uninstall

### ISSUE THREAD

**Issue by GreenberryServiceAccount** [ddworken/hishtory#222] opened 2024-06-18 07:14 UTC
After **every** command I run in my terminal I get an error about the hishtory API being unreachable:

```
hishtory fatal error at github.com/ddworken/hishtory/hishtory.go:396: failed to POST /api/v1/submit?source_device_id=50171bec-c36f-4660-aac7-f949e44e9b14: Post "https://api.hishtory.dev/api/v1/submit?source_device_id=50171bec-c36f-4660-aac7-f949e44e9b14": net/http: TLS handshake timeout
```

Also, the `uninstall` command gives an error.

```
hishtory uninstall
Are you sure you want to uninstall hiSHtory and delete all locally saved history data [y/N]y
2024/06/18 09:13:00 hishtory fatal error at github.com/ddworken/hishtory/hishtory.go:99: open /Users/sanderbruggeman/.config/fish/config.fish: no such file or directory
```

I'm not really using histhory in practice, so I'd like to uninstall it completely. Is there any other way to remove hishtory?

**Comment by ddworken** [comment] 2024-07-05 01:33
Hi! I'm wondering: Are you running an older version of hishtory? I suspect you are since both of the issues you're running into here I believe are fixed in the latest version of hishtory. Specifically:

1. When the server is down, hishtory will detect this and continue to function in offline mode 
2. hishtory will auto-detect when certain files don't exist when uninstalling and skip them

In terms of working around this, the easiest solution is probably to just run `hishtory update` and then `hishtory uninstall`.

**Comment by ddworken** [comment] 2024-08-25 19:29
I'm closing this out since I can't reproduce this issue, but if you or anyone does run into this again, please let me know!

**Closed by ddworken** 2024-08-25 19:29 UTC
