### ISSUE TITLE
API connection error in a self-hosted environment

### ISSUE THREAD

**Issue by asitemade4u** [ddworken/hishtory#109] opened 2023-09-17 21:08 UTC
Hi,
And thank you for Hishtory.
Unfortunately, I recently began getting errors from all the clients connected to my self-hosted Hishtory server, such as:

```error
2023/09/17 17:03:42 hishtory v0.215 fatal error at github.com/ddworken/hishtory/client/cmd/saveHistoryEntry.go:176: failed to POST https://hsy.qtpl.net/api/v1/submit?source_device_id=<hidden>: status_code=403
```

I followed the thread at #107 and found their errors consistent with mine.
So, I did the following:

- updated the docker image of the server to the last one
- checked the connection  of the server to the Postgres database
- checked the status of the server by doing `https://<server_address>/healthcheck`

Everything looks fine and yet...

Please help me get rid of those pesky error messages.
S.

**Comment by ddworken** [comment] 2023-09-17 21:13
Hmm, I don't think there is anything in our server code that would return a 403 error code. Is it possible that there is some proxy/LB that is intercepting the response from your self-hosted server and returning a 403 error code?

**Comment by ddworken** [comment] 2023-09-23 20:01
Thanks for the details! I spent some time looking at this, and sadly I'm unable to reproduce it. I tried running the LinuxServer.io docker image, and it seemed to work fine without any 403 errors. And looking at the docker image, I don't see anything in there that would cause it to return a 403 error, so I think the 403 error must be coming from something else in your environment (a proxy/LB somewhere?). 

Closing, but if you do figure this out, please let me know! And if anyone else does run into this issue, please reopen this issue.

**Closed by ddworken** 2023-09-23 20:01 UTC
