### ISSUE TITLE
Let hishtory use all of the log files generated by it.

### ISSUE THREAD

**Issue by hongyi-zhao** [ddworken/hishtory#224] opened 2024-06-25 02:13 UTC
I found that `hishtory` will generate so many separate log files as follows:

```shell
werner@x13dai-t:~/.hishtory$ ls *log
hishtory-2024-05-27T07-57-46.446.log  hishtory-2024-06-07T08-14-07.310.log  hishtory-2024-06-14T11-29-31.727.log  hishtory-2024-06-23T10-20-32.236.log  hishtory.log
hishtory-2024-06-03T05-00-32.232.log  hishtory-2024-06-11T12-29-57.273.log  hishtory-2024-06-21T10-36-19.281.log  hishtory-2024-06-24T05-14-51.347.log
```
But it seems that it only queries the `hishtory.log` by default. So, how can I let it use all of these log files?

Regards,
Zhao

**Comment by ddworken** [comment] 2024-08-25 18:31
Duplicate of #219

**Closed by ddworken** 2024-08-25 18:31 UTC
